### ISSUE TITLE
Fix: Keys become unaligned when using bootstrap

### ISSUE THREAD

**Issue by kugarocks** [stuartmemo/qwerty-hancock#31]
In bootstrap, the box-sizing is border-box. 

``` css
* {
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}
```

To fix this, just overwrite it when styling the white keys.

``` js
key.el.style.boxSizing = 'content-box';
```
